# Generated by Django 6.1 on 2026-08-18 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('targetSets', models.PositiveSmallIntegerField()),
                ('targetReps', models.CharField(help_text='e.g. "8-12", "5", "AMRAP"', max_length=15)),
                ('idExercise', models.ForeignKey(db_column='idExercise', on_delete=django.db.models.deletion.PROTECT, related_name='routine_entries', to='catalog.exercise')),
            ],
            options={
                'db_table': 'routines',
                'ordering': ['idUserSplit', 'idSplitDay', 'order'],
            },
        ),
    ]
