# Generated by Django 6.1 on 2026-08-18 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routines', '0001_initial'),
        ('splits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='idSplitDay',
            field=models.ForeignKey(db_column='idSplitDay', on_delete=django.db.models.deletion.PROTECT, related_name='routines', to='splits.splitday'),
        ),
        migrations.AddField(
            model_name='routine',
            name='idUserSplit',
            field=models.ForeignKey(db_column='idUserSplit', on_delete=django.db.models.deletion.CASCADE, related_name='routines', to='splits.usersplit'),
        ),
        migrations.AddIndex(
            model_name='routine',
            index=models.Index(fields=['idUserSplit'], name='routines_idUserS_5bb612_idx'),
        ),
        migrations.AddIndex(
            model_name='routine',
            index=models.Index(fields=['idSplitDay'], name='routines_idSplit_ea7ed7_idx'),
        ),
        migrations.AddIndex(
            model_name='routine',
            index=models.Index(fields=['idExercise'], name='routines_idExerc_5182ed_idx'),
        ),
        migrations.AddConstraint(
            model_name='routine',
            constraint=models.CheckConstraint(condition=models.Q(('targetSets__gt', 0)), name='routine_target_sets_positive'),
        ),
    ]
