# Generated by Django 6.1 on 2026-08-18 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Split',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'splits',
                'db_table': 'splits',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SplitDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('dayNumber', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=80)),
                ('idSplit', models.ForeignKey(db_column='idSplit', on_delete=django.db.models.deletion.CASCADE, related_name='days', to='splits.split')),
            ],
            options={
                'db_table': 'split_days',
                'ordering': ['idSplit', 'dayNumber'],
            },
        ),
        migrations.CreateModel(
            name='UserSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField(blank=True, null=True)),
                ('isActive', models.BooleanField(default=True)),
                ('idSplit', models.ForeignKey(db_column='idSplit', on_delete=django.db.models.deletion.PROTECT, related_name='adopters', to='splits.split')),
            ],
            options={
                'db_table': 'user_splits',
                'ordering': ['-startDate'],
            },
        ),
    ]
