# Generated by Django 6.1 on 2026-08-18 04:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('splits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usersplit',
            name='idUser',
            field=models.ForeignKey(db_column='idUser', on_delete=django.db.models.deletion.CASCADE, related_name='user_splits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='splitday',
            constraint=models.CheckConstraint(condition=models.Q(('dayNumber__gte', 1), ('dayNumber__lte', 7)), name='split_day_number_range'),
        ),
        migrations.AlterUniqueTogether(
            name='splitday',
            unique_together={('idSplit', 'dayNumber')},
        ),
        migrations.AddIndex(
            model_name='usersplit',
            index=models.Index(fields=['idUser', 'isActive'], name='user_splits_idUser_fa283b_idx'),
        ),
        migrations.AddIndex(
            model_name='usersplit',
            index=models.Index(fields=['idSplit'], name='user_splits_idSplit_0febc5_idx'),
        ),
    ]
