# Generated by Django 6.1 on 2026-08-18 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('routines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('workoutDate', models.DateTimeField(auto_now_add=True)),
                ('setNumber', models.PositiveSmallIntegerField()),
                ('repetitions', models.PositiveSmallIntegerField()),
                ('kg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rpe', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('idIntensityTechnique', models.ForeignKey(blank=True, db_column='idIntensityTechnique', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workouts', to='catalog.intensitytechnique')),
                ('idRoutine', models.ForeignKey(db_column='idRoutine', on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='routines.routine')),
            ],
            options={
                'db_table': 'workouts',
                'ordering': ['-workoutDate'],
                'indexes': [models.Index(fields=['workoutDate'], name='workouts_workout_1ff346_idx'), models.Index(fields=['idRoutine'], name='workouts_idRouti_dad740_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('repetitions__gte', 0)), name='workout_repetitions_non_negative'), models.CheckConstraint(condition=models.Q(('kg__gte', 0)), name='workout_kg_non_negative'), models.CheckConstraint(condition=models.Q(('setNumber__gt', 0)), name='workout_set_number_positive')],
            },
        ),
    ]
