# Generated by Django 6.1 on 2026-08-18 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntensityTechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'intensity_techniques',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Muscle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('imgUrl', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'muscles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('videoUrl', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'db_table': 'exercises',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='exercises_name_26c749_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExerciseMuscle',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('stabilizer', 'Stabilizer')], default='primary', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('idExercise', models.ForeignKey(db_column='idExercise', on_delete=django.db.models.deletion.CASCADE, related_name='muscles', to='catalog.exercise')),
                ('idMuscle', models.ForeignKey(db_column='idMuscle', on_delete=django.db.models.deletion.PROTECT, related_name='exercises', to='catalog.muscle')),
            ],
            options={
                'db_table': 'exercise_muscles',
                'indexes': [models.Index(fields=['idExercise'], name='exercise_mu_idExerc_b25187_idx'), models.Index(fields=['idMuscle'], name='exercise_mu_idMuscl_52909f_idx')],
                'unique_together': {('idExercise', 'idMuscle', 'role')},
            },
        ),
    ]
